### ISSUE TITLE
Timeout during adding g8os node to the zerotier network

### ISSUE THREAD

**Issue by john-kheir** [g8os/resourcepool#120]
The g8os node has already been added to the zerotier network but something went wrong during creating storage pool
![jo1](https://cloud.githubusercontent.com/assets/15011431/25335438/539fd028-28f3-11e7-9712-4700eb526f8d.png)
![jo2](https://cloud.githubusercontent.com/assets/15011431/25335439/554fd63e-28f3-11e7-993a-4e8065b6c8e7.png)

**Comment by Dinaamagdy** [comment]
grid : 48baa90
js:  d043e6e
