### ISSUE TITLE
vms_apis: PUT nodes/{nodeid}/vms/{vmid} doesn't work

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#126]
### API
``` PUT nodes/{nodeid}/vms/{vmid}```

### steps
- create vm **vm-x1**
- update **vm-x1** memory and cpu 
- get vm1 details
 
### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25431027/2496c3b2-2a7f-11e7-9f72-b26ddfaff3e3.png)

### Actual result
**vm-x1** memory and cpu were not updated
![image](https://cloud.githubusercontent.com/assets/24386820/25431121/87659b80-2a7f-11e7-8f38-d19058dd2f15.png)

**Comment by ahmedelsayed-93** [comment]
# same issue when update nics and disk

###software version
grid faeae03
jumpscale 92c7a2d

**Comment by ahmedelsayed-93** [comment]
issue still exists 
### SV
js 1a3b812
grid 67e7d28

**Comment by khaledkbadr** [comment]
Blocked on `https://github.com/g8os/core0/issues/220`

**Comment by ahmedelsayed-93** [comment]
### SV
js 507d2d0
resourcepool 81137e0
core0 56c40ef
