### ISSUE TITLE
AYS auto discovering nodes service doesn't recognize the deleted nodes

### ISSUE THREAD

**Issue by islamTaha12** [g8os/resourcepool#151]
It seems that the zerotire system doesn't remove the dead machines from the nw so it infected our system and there is no way to recognize that the g8os node has been stopped or removed.

**Steps**
1- create two g8os nodes
2- add them to zerotire nw
3- start an AYS server and add it to the same nw
4- add the auto-discovering blueprint 
5- make sure that the AYS recognized those two nodes
6- remove one of those nodes (delete its packet machine)
7- check the AYS nodes list

**Actual result**
Ays still list two nodes however there is only one live node.

![screenshot from 2017-05-02 14-26-48](https://cloud.githubusercontent.com/assets/17981089/25617755/1efb62ae-2f44-11e7-98c2-1b879faa5c6f.png)

![screenshot from 2017-05-02 14-27-00](https://cloud.githubusercontent.com/assets/17981089/25617760/268f8d56-2f44-11e7-9e82-7a51cdbb90b8.png)

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/g8os/grid/pull/162

**Comment by ahmedelsayed-93** [comment]
issue still exists

jumpscale : 68832ff8
grid : f100e6a

**Comment by ahmedelsayed-93** [comment]
### SV
js 1a3b812
grid 67e7d28
