### ISSUE TITLE
bridges_apis: creating bridge with invalid parameters returns internal server error instead of 400

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#152]
### API
```POST /nodes/{nodeid}/bridges```

this issue appears when i set ```name``` or ```networkMode``` or ``` hwaddr```  or ```settings > (cidr ,start, stop)```   with invalid value
* the invalid value for name parameter is special characters

**Comment by serboctor** [comment]
Related to #155

**Comment by serboctor** [comment]
Extra input from Ahmed:
- Invalid networkMode: any value except (none , static and dnsmasq)
- Invalid hwaddr: invalid mac address
- Invalid (cidr ,start, stop) wrong ip address format

**Comment by ahmedelsayed-93** [comment]
### SV
jumpscale : 68832ff8
grid : f100e6a
