### ISSUE TITLE
network.g8os does not create ays container service

### ISSUE THREAD

**Issue by grimpy** [g8os/resourcepool#154]
Network.g8os creates ovs container but does not register it properly as ays service.

**Comment by Dinaamagdy** [comment]
## SV
resourcepool: 743671b56a2a9d7123c3a40a9450c515e9610276
jumpscale: eb5ed3371093f048951be8d9b631d0ca922c06a2

**Comment by Dinaamagdy** [comment]
## SV :
jumpscale:  c5d489e6de28e2c63f4016eb890579aa610aec35 
resourcepool : 9e275cdb15c7c5ec4f98a31a9fdd3429141a90b7
