### ISSUE TITLE
Need better validation of names and ids used for service names in ays

### ISSUE THREAD

**Issue by FastGeert** [g8os/resourcepool#155]
I was struggling this morning fro more than 2 hours until i found out that i was using spaces in the api post field that underlying was going to be used as the service name in ays.

The grid api server just returns a 500, and in the body it returns 404, all very confusing.

In the log of the grid server I only found:
```
ERRO[0006] error executing blueprint for container Geert's echo service creation : 404 Not Found
192.168.193.33 - - [03/May/2017:07:46:23 +0000] "POST /nodes/0cc47a3b3d6a/containers HTTP/1.1" 500 26
```

**Comment by serboctor** [comment]
I added a validation on the payloads of the apis to check that any attribute used as a service name matches the regex allowed by ays. Ays service names can only contain: alpha, numerics, -, _ and .
The APIs affected by this fix:
- BridgeCreate: name.
- CreateContainer: name.
- FilesystemCreate: name.
- StoragePoolCreate: name.
- VMCreate: id.
- VMMigrate: nodeid.
- ZeroTierJoin: nwid.
- CreateSnapshot.
- ClusterCreate: label.
- VdiskCreate: id.

**Comment by ahmedelsayed-93** [comment]
### SV
jumpscale : 68832ff8
grid : f100e6a
