### ISSUE TITLE
Add validation for enums

### ISSUE THREAD

**Issue by serboctor** [g8os/resourcepool#170]
There is no validation done for any attribute that is expected to belong to a certain enum.
For example, in the bridge create, the networkMode is expected to be one of ["none", "static", "dnsmasq"]. If another value is supplied, the api doesn't validate and return a bad request which result in a crash in ays.

All payloads that contain enums should be validated and if a value other than the expected is supplied, the api should return a 400.

**Comment by serboctor** [comment]
APIs affected by this fix:
- CreateContainer: nic type
- StoragePoolCreate: dataprofile and metadataprofile
- CreateVM: nics type
- UpdateVm: nics type
- VdiskCreate: vdisktype
- ClusterCreate:  drivetype

**Comment by ahmedelsayed-93** [comment]
### SV
jumpscale : 68832ff8
grid : f100e6a
