### ISSUE TITLE
storageclusters_apis: delete storagecluster api doesn't work

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#175]
### API
``` DELETE /storageclusters/{storageclusterid}```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25779790/a2596406-331e-11e7-860c-537f01de97ac.png)

**node disks status**
![image](https://cloud.githubusercontent.com/assets/24386820/25779801/df7a4242-331e-11e7-9319-abcedbfbe0f5.png)

### SV
jumpscale : 68832ff8
grid : f100e6a

**Comment by ahmedelsayed-93** [comment]
![image](https://cloud.githubusercontent.com/assets/24386820/25848698/c848f37c-34bb-11e7-9f7f-a3b35ae52d5c.png)

![image](https://cloud.githubusercontent.com/assets/24386820/25848714/dc11fa34-34bb-11e7-89c8-44b5387fe2a6.png)

### SV
js 1a3b812
grid 67e7d28

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/g8os/resourcepool/pull/187

**Comment by ahmedelsayed-93** [comment]
when deleting the storagecluster disk still mounted 
### SV
grid 48baa90
js d043e6e

**Comment by ahmedelsayed-93** [comment]
### SV
js 441b344
resourcepool  da19c73
