### ISSUE TITLE
make sure api's can be found

### ISSUE THREAD

**Issue by despiegk** [g8os/resourcepool#176]
![image](https://cloud.githubusercontent.com/assets/6021844/25781404/1f231b06-333a-11e7-89ab-1856a5c539cf.png)

**Comment by despiegk** [comment]
https://rawgit.com/g8os/grid/1.1.0-alpha/raml/api.html#

**Comment by khaledkbadr** [comment]
It can be found in the [README](https://github.com/g8os/resourcepool/blob/1.1.0-alpha/README.md)

**Comment by ahmedelsayed-93** [comment]
### SV
grid 67e7d28
