### ISSUE TITLE
DELETE /node/containers/filesystem API doesn't work

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/resourcepool#179]
## Steps: 
- Use ` DELETE /node/containers/filesystem ` API 
- Use it again for same filesystem
 - Check exist of file in node 
## Response: 
- Use Api again for delete same file ,doesn't result  error 
![selection_311](https://cloud.githubusercontent.com/assets/24386802/25784435/6371e2aa-336d-11e7-8770-54619bd355a6.png)

- File still exist in node 
![selection_312](https://cloud.githubusercontent.com/assets/24386802/25784478/0b003a3a-336e-11e7-938b-b7788b6c41aa.png)

## SV
jumpscale: 0a0a1f175cc912ce55581f9017b71e82e974e6ff
resourcepool : 5ab5ac39a6f84ec01ad98f1d9eb8235314a8c707

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduce works with me

**Comment by Dinaamagdy** [comment]
## SV
resourcepool : 60c9e8f7d5d42ef90ff484fdc2c54f8e51411d2a
