### ISSUE TITLE
Create container with nics type default fail 

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/resourcepool#180]
## Steps : 
- Create container using API `Post /nodes/container' with nics type default and no value in nic Id as written in doc.

## Response: 
Bad request need to id .
![selection_317](https://cloud.githubusercontent.com/assets/24386802/25796722/fef05f1e-33da-11e7-9806-f70a9d6b3659.png)

## SV
 resourcepool : 5ab5ac39a6f84ec01ad98f1d9eb8235314a8c707

**Comment by abdulrahmantkhalifa** [comment]
the grid no longer supports none type in the id , if u need to work pass either a zerrotierid vxlanid or vlantag

**Comment by Dinaamagdy** [comment]
what is the Id value for default type ?

**Comment by Dinaamagdy** [comment]
#SV 
resourcepool: 67e7d28a1207a57114a353093fd8261197c42d39
