### ISSUE TITLE
vms_apis: PUT /node/{nodeid}/vms/{vmid} with non-existing vmid returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#185]
### API
```PUT /node/{nodeid}/vms/{vmid}```

### request and response
![image](https://cloud.githubusercontent.com/assets/24386820/25847920/6038e060-34b8-11e7-95e0-392b0661f63b.png)

### SV
js 1a3b812
grid 67e7d28

**Comment by serboctor** [comment]
I couldn't reproduce the error. It always gives me 204 which is also incorrect since it should return 404 for an inexistent vm. Fix done in the api.

**Comment by ahmedelsayed-93** [comment]
### SV
js  eb5ed33
grid 8faf72b
