### ISSUE TITLE
resourcepool api server fails to serve storagecluster details when the storage_cluster service is in status error

### ISSUE THREAD

**Issue by FastGeert** [g8os/resourcepool#196]
Was trying to deploy a 10 node / 50 server storagecluster on packet. This failed in the init step of the storage_cluster service. In the end, the storage_cluster service is in error.

![afbeelding](https://cloud.githubusercontent.com/assets/15246294/25900713/a819dd58-3594-11e7-98e2-17dd548d1985.png)

And this results in the following when querying the api

![afbeelding](https://cloud.githubusercontent.com/assets/15246294/25900574/2d8733ec-3594-11e7-9173-2d31a8ed9941.png)

**Comment by grimpy** [comment]
Can't reproduce
