### ISSUE TITLE
Delete all jobs Api doesn't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/resourcepool#197]
## API
Delete `/nodes/jobs`

## Response 
It keep loading and request doesn't send to grid server .
![selection_326](https://cloud.githubusercontent.com/assets/24386802/25900743/be14f750-3594-11e7-83cb-28a2c9f62475.png)

## SV
resourcepool: 743671b56a2a9d7123c3a40a9450c515e9610276

**Comment by serboctor** [comment]
The fix for this requires updating core0.

**Comment by Dinaamagdy** [comment]
#SV 
resourcepool: a30a8b47653db98bbb80d4039a7e5722ccfa156c
