### ISSUE TITLE
Freshly created vms are always in state error

### ISSUE THREAD

**Issue by FastGeert** [g8os/resourcepool#203]
![afbeelding](https://cloud.githubusercontent.com/assets/15246294/25907416/b08481ec-35a7-11e7-8654-0867e36996db.png)

**Comment by serboctor** [comment]
Added state "deploying". The vm will now be "deploying" until completely created and started.

**Comment by ahmedelsayed-93** [comment]
### SV
js 507d2d0
resourcepool 81137e0
core0 56c40ef
