### ISSUE TITLE
Create build script for tlog server flist and upload flist to the hub

### ISSUE THREAD

**Issue by zaibon** [g8os/resourcepool#236]
Repo of the tlog: https://github.com/g8os/blockstor/tree/master/tlog

**Comment by grimpy** [comment]
This was added to the blockstor flist

**Comment by grimpy** [comment]
https://hub.gig.tech/gig-official-apps/blockstor-master.flist
https://github.com/g8os/resourcepool/blob/master/buildscripts/builder-blockstor.sh
