### ISSUE TITLE
bridges list API : list not created bridge

### ISSUE THREAD

**Issue by Dinaamagdy** [g8os/resourcepool#238]
## Steps 
- create bridge with dnsmasq networkmode with start and end ip values in settings.
- create another bridge with same value for end and start ip value , will fail  as shown 
![image](https://cloud.githubusercontent.com/assets/24386802/26108125/d0fc7a62-3a4b-11e7-9f32-1d944fe51b7e.png)
###  list bridges with get /node/bridges API 

![selection_346](https://cloud.githubusercontent.com/assets/24386802/26108194/1299b778-3a4c-11e7-8f88-a6e1523db58c.png)
![selection_347](https://cloud.githubusercontent.com/assets/24386802/26108356/891b9ec0-3a4c-11e7-993f-12f578c37f57.png)

### try to delete it 
```
{
  "error": "\n\njob job: bridge!test_bridge (stop) done sucessfuly\n\njob job: bridge!test_bridge (uninstall) done sucessfuly\n\nRuntimeError: failed to list delete: \"Link not found\"\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.5/concurrent/futures/thread.py\", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/tmp/actions/bridge/f54dc7b3c7c1fce37fb701e4fdf8f759.py\", line 48, in delete\n    cl.bridge.delete(service.name)\n  File \"/usr/local/lib/python3.5/dist-packages/g8core/client.py\", line 884, in delete\n    raise RuntimeError('failed to list delete: %!s(MISSING)' %!r(MISSING)esult.data)\nRuntimeError: failed to list delete: \"Link not found\""
}
```
## SV
8bc19dc3297d1fe620ad1d0655691528f5eb545d

**Comment by serboctor** [comment]
Add status "error" to bridge status. If any error occurs during the bridge creation on core0, the status will be set to error.

**Comment by john-kheir** [comment]
## Versions
Verified on 
core0-v: master c1513139664d3e782ddc72b8ea65c7376e11b19e
resourcepool-v: master  10a8901f3a26e9ee6275c322bf32307f4c2ed84f
