### ISSUE TITLE
nodes_apis: delete non-existing bridge returns 204 instead of 404

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#258]
### API
```DELETE nodes/{{nodeid}}/bridges/{{bridgeid}}```

### response  & request 
![image](https://cloud.githubusercontent.com/assets/24386820/26281979/4aeb2436-3e07-11e7-8a74-8bed3dcb5a18.png)

### SV
resourcepool af2d6b3

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduce :
![image](https://cloud.githubusercontent.com/assets/15012414/26284992/e074137a-3e46-11e7-873e-13de0de0bd26.png)
SV
af2d6b32c8b16dc151e7343f16d1edbdc50f7739

**Comment by john-kheir** [comment]
## Versions
Verified on 
core0-v: master c1513139664d3e782ddc72b8ea65c7376e11b19e
resourcepool-v: master  10a8901f3a26e9ee6275c322bf32307f4c2ed84f
