### ISSUE TITLE
Should be possible to start jobs on containers, and not be possible to start processes

### ISSUE THREAD

**Issue by FastGeert** [g8os/resourcepool#261]
Today it is not possible to start a job, on the other hand, starting a process is possible. The weird thing, if you start a process is that you get a link to a job, which is completely the world up side down.

So we should replace the create process with create job:

![afbeelding](https://cloud.githubusercontent.com/assets/15246294/26344128/d7ee8f38-3f9e-11e7-9e44-3d17cb502a78.png)

**Comment by Dinaamagdy** [comment]
## SV :
resourcepool:  e1bb4cbe0cf7014f9606efac58d12331fa635694
