### ISSUE TITLE
Implement network config for g8os node

### ISSUE THREAD

**Issue by zaibon** [g8os/resourcepool#80]
Currently AYS service node.g8os consumes network services.
We need to implement the network service so it configure configuration of the network is done on the node every time it starts

**Comment by mie00** [comment]
A network service consumes the following:
* devices (such as bridges) with arguments to do static and dhcp configuration.
* routes
* Firewall rules

devices:
* physical, which is detected from the nodes
* virtual

routes:
* manually added routes, with an option to override an already existing conflict or fail
* a default route that can be assigned to a bridge (for dhcp)

firewall rules:
* rules for accepting connection, forwarding, natting etc.
should we make a default config?

How does this configuration gets applied to the g8os node. Do we assume that the g8os has no network configuration before running this?

**Comment by mie00** [comment]
Based on a discussion with @grimpy. This configuration will be done using the management (or zerotier?) interface, this service will get how to connect through them from the node service.

These two interfaces will not be mentioned in the configuration of the network service, and they will be dynamically added to it at the init time.

**Comment by muhamadazmy** [comment]
First:
- No routing table mgmt is needed
- No firewall rules are needed (natting is handled by core0 in brdige creation)

Plus: We need to do this management via OVS, as follows:
- Create OVS container with the correct params (`host_network=True, tags=['ovs']`)
- Create your networking infrastructure
```python
ovscl.json('ovs.bridge-add', {"bridge": "backplane"})
ovs.json('ovs.vlan-ensure', {'master': 'backplane', 'vlan': 2313, 'name':'vxbackend'})
```
- Then u need to connect your backplane to the internet vi `ovs.port-add` or `ovs.bond-add` depends on your setup.
- You probably also need to run `dhcpc` on the backplane to get an IP.
