### ISSUE TITLE
storagepools_apis: Add extra devices to storagepool doesn't work

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#87]
### API
```POST /nodes/{nodeid}/storagepools/{storagepoolname}/devices```

### Steps
- create storagepool 
- add devices to this storagepool
- list storagepool devices

![image](https://cloud.githubusercontent.com/assets/24386820/25127029/a05a41aa-2434-11e7-94fe-c0ddf47ba9ad.png)

### actual result
![image](https://cloud.githubusercontent.com/assets/24386820/25127044/b3b8ead0-2434-11e7-9c74-f6b10fd83ab4.png)

### software versions

JUMPSACLE_BRANCH = "8.2.0"
GRID_API_BRANCH = "1.1.0-alpha"
AYS_TEMPLATE_BRANCH = "1.1.0-alpha

**Comment by ahmedelsayed-93** [comment]
verification process is blocked because of #119

**Comment by zaibon** [comment]
#119 has been moved to verification, you should be able to unblock this one

**Comment by ahmedelsayed-93** [comment]
### Scenario 

- create storagepool **sp1** with device **vdb**
- add device **vdc** to  storagepool **sp1**
![image](https://cloud.githubusercontent.com/assets/24386820/25490700/e3f36dfc-2b6d-11e7-9dd5-a15ff8eaa9d5.png)

### Actual results 
- device **vdc** was not mounted and didn't get uuid 
**response from python client**
![image](https://cloud.githubusercontent.com/assets/24386820/25490734/fc43b290-2b6d-11e7-8b6a-e5370928644d.png)

**grid response**
![image](https://cloud.githubusercontent.com/assets/24386820/25490718/ecbfbf12-2b6d-11e7-8780-b4180844146e.png)

**Comment by serboctor** [comment]
The fix for this was done in jumpscale code.

**Comment by ahmedelsayed-93** [comment]
### SV
jumpscale : 68832ff8
grid : f100e6a
