### ISSUE TITLE
storagepools_apis : device status is always empty

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/resourcepool#93]
### Steps
- Create storagepool and add extra devices to it.
- list this storagepool devices

### response and request
![image](https://cloud.githubusercontent.com/assets/24386820/25178197/15bc9d14-2505-11e7-939e-809e5e37f4d5.png)

### Expected result 
status should be one of **healthy**, **removing**

**Comment by ahmedelsayed-93** [comment]
verification process is blocked because of #119

**Comment by zaibon** [comment]
#119 has been moved to verification, you should be able to unblock this one

**Comment by serboctor** [comment]
Removed state_verification because the feature is not implemented yet.

**Comment by ahmedelsayed-93** [comment]
### SV
js 4a39bad
resourcepool  02c0ebf
